const char imgFile[][30] = {
	"textures/startBg.jpg",
	"textures/light.png",
	"textures/startButton.png",
	"textures/smallStone.png",
	"textures/bigStone.png",
	"textures/diamond.png",
	"textures/gold.png",
	"textures/bag.png",
	"textures/goalBg.png",
	"textures/gameBg.png",
	"textures/hook.png",
	"textures/line.png",
	"textures/sgold.png",
	"textures/gameBg1.png",
	"textures/gameBg2.png",
	"textures/img_duongray.png",
	"textures/cot1.png",
	"textures/cot2.png",
	"textures/img_obj1.png",
	"textures/img_obj2.png",
	"textures/img_obj3.png",
	"textures/img_obj4.png",
	"textures/img_obj5.png",
	"textures/img_obj6.png",
	"textures/img_obj7.png",
	"textures/img_obj8.png",
	"textures/img_obj9.png",
	"textures/img_obj10.png",
	"textures/img_obj11.png",
	"textures/img_obj12.png"
};

const char sodFile[][30] = {
	"sounds/mouseIn.wav",
	"sounds/dig.mp3",
	"sounds/explosive.wav",
	"sounds/highValue.wav",
	"sounds/lowValue.wav",
	"sounds/norValue.wav",
	"sounds/pull.wav",
	"sounds/score1.wav",
	"sounds/score2.wav"
};

